version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3001
    ports:
      - "3001:3001"
    restart: always
    networks:
      - planning-poker-network

  # Frontend service
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
      args:
        - BACKEND_URL=http://localhost:3001
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
    networks:
      - planning-poker-network

# Define a network for services to communicate
networks:
  planning-poker-network:
    driver: bridge
